Repository ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t4-pmv-ads-2024-1-e1-proj-fila-facil, pull requests merged in 2024-06, with the labels that each got.

#97 feat: Chat com o restaurante
  src/README.md
  src/assets/css/cadastroStyle.css
  src/assets/css/cardapioStyle.css
  src/assets/css/carrinhoStyle.css
  src/assets/css/chatStyle.css
  src/assets/css/pedidosstyle.css
  src/assets/css/perfilStyle.css
  src/assets/css/restauranteStyle.css
  src/assets/js/cardapioCarouselScript.js
  src/assets/js/carrinho.js
  src/assets/js/chat.js
  src/assets/js/perfilScript.js
  src/assets/js/renderPratosCardapioUtils.js
  src/assets/js/restaurantes.js
  src/pages/cardapio.html
  src/pages/pedidos.html
  src/pages/perfil.html
  src/pages/restaurantes.html
Labels: documentation, enhancement

#92 feat: Renderização da página de pedidos via JavaScript
  src/README.md
  src/assets/css/pedidosstyle.css
  src/assets/js/carrinho.js
  src/assets/js/pedidos.js
  src/assets/js/pedidosCarrousel.js
  src/assets/js/restauranteJson.js
  src/pages/pedidos.html
Labels: enhancement

#99 feat: Implementação do cálculo de estoque nos card página de cardápio
  src/README.md
  src/assets/css/cardapioStyle.css
  src/assets/js/carrinho.js
Labels: enhancement

#101 feat: Página de gerência do restaurante e cardápio
  src/README.md
  src/assets/css/adminStyle.css
  src/assets/js/adminScript.js
  src/assets/js/cardapioCarouselScript.js
  src/assets/js/restauranteJson.js
  src/assets/js/restaurantes.js
  src/pages/admin.html
Labels: enhancement

#104 feat: Receita de vendas
  src/README.md
  src/assets/js/adminScript.js
  src/assets/js/carrinho.js
  src/pages/admin.html
Labels: enhancement

#105 doc: Registro de Testes de Software
  doc/08-Registro de Testes de Software.md
Labels: documentation

#106 doc: Atualização programação de funcionalidades
  doc/06-Programação de Funcionalidades.md
  doc/image.png
  doc/img/funcionalidades-cadastroprato.png
  doc/img/funcionalidades-carrinho.png
  doc/img/funcionalidades-carrinhocompra.png
  doc/img/funcionalidades-chat.png
  doc/img/funcionalidades-cupomdesconto.png
  doc/img/funcionalidades-estoque.png
  doc/img/funcionalidades-faturamento.png
  doc/img/funcionalidades-restaurante.png
Labels: documentation

#100 doc: Plano de testes de software
  doc/07-Plano de Testes de Software.md
  src/README.md
Labels: documentation

#113 feat: Criada validação para usuário logado
  src/README.md
  src/assets/js/cadastro.js
  src/assets/js/checkLogin.js
  src/assets/js/login.js
  src/assets/js/perfilScript.js
  src/pages/admin.html
  src/pages/cardapio.html
  src/pages/pedidos.html
  src/pages/perfil.html
  src/pages/restaurantes.html
Labels: bug, enhancement

#114 feat: Carregar arquivo .json em páginas necessárias
  src/README.md
  src/assets/js/adminScript.js
  src/assets/js/cardapioCarouselScript.js
  src/assets/js/carrinho.js
  src/assets/js/loadJson.js
  src/assets/js/restaurante.json
  src/assets/js/restauranteJson.js
  src/assets/js/restaurantes.js
  src/pages/admin.html
  src/pages/cardapio.html
  src/pages/perfil.html
  src/pages/restaurantes.html
Labels: bug, enhancement

#115 feat: Buscar cartões de pagamento via localStorage
  src/README.md
  src/assets/js/carrinho.js
  src/pages/cardapio.html
  src/pages/pedidos.html
  src/pages/restaurantes.html
Labels: enhancement

#117 feat: Reset de senha pela página de login
  src/README.md
  src/assets/css/login.css
  src/assets/js/login.js
  src/assets/js/pass-recovery.js
  src/pages/login.html
  src/pages/pass-recovery.html
Labels: enhancement

#120 feat: Adicionado links das imagens nos pratos do cardápio
  src/README.md
  src/assets/js/restaurante.json
Labels: enhancement
