Repository ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t4-pmv-ads-2024-1-e1-proj-fila-facil, pull requests merged in 2024-05, with the labels that each got.

#44 Create LICENSE
  LICENSE
Labels: documentation

#43 feat: Criação da página home e funcionalidades
  doc/01-Documentação de Contexto.md
  doc/02-Especificação do Projeto.md
  doc/04-Projeto de Interface.md
  src/README.md
  src/assets/css/homeStyle.css
  src/assets/img/bannerAbout.jpg
  src/assets/img/bannerMain.jpg
  src/assets/img/iconeFilaFacil.png
  src/assets/img/logoFilaFacil.png
  src/assets/img/serviceCardOne.jpg
  src/assets/img/serviceCardThree.jpg
  src/assets/img/serviceCardTwo.jpg
  src/assets/js/homeCarouselScript.js
  src/index.html
Labels: documentation, enhancement

#52 feat: adição da página de pedidos
  src/README.md
  src/assets/css/Pedidos.css
  src/assets/img/pedidos/arcanjos2.jpeg
  src/assets/img/pedidos/italiano.png
  src/assets/img/pedidos/logoFilaFacil.png
  src/assets/img/pedidos/marguerita.jpeg
  src/assets/img/pedidos/nabrasa.jpeg
  src/assets/js/Pedidos.js
  src/pages/Pedidos.html
Labels: enhancement

#55 fix: Correção na pagina de pedidos
  src/README.md
  src/assets/css/pedidosstyle.css
  src/assets/js/Pedidos.js
  src/pages/Pedidos.html
Labels: bug

#56 feat: Funcionalidade em js da página de cadastro
  src/README.md
  src/assets/css/cadastroStyle.css
  src/assets/js/cadastro.js
  src/index.html
  src/pages/cadastro.html
Labels: enhancement

#53 feat: Página Restaurante
  src/README.md
  src/assets/css/restauranteStyle.css
  src/assets/img/asianfood.jpg
  src/assets/img/banner-res.png
  src/assets/img/doces-delicias.png
  src/assets/img/saladaria.png
  src/assets/img/slide1.jpg
  src/assets/img/slide2.jpg
  src/assets/img/slide3.jpg
  src/assets/img/slide4.jpg
  src/assets/img/slide5.jpg
  src/assets/img/slide6.jpg
  src/assets/img/slide7.webp
  src/assets/img/slide8.webp
  src/pages/restaurantes.html
Labels: enhancement

#49 feat: Criação da página de login
  src/README.md
  src/assets/css/Login.css
  src/assets/js/Login.js
  src/pages/Login.html
Labels: enhancement

#61 feat: Criação da página carrinho
  src/README.md
  src/assets/css/carrinhoStyle.css
  src/assets/js/carrinho.js
  src/pages/carrinho.html
Labels: enhancement

#60 doc: Template padrão da aplicação
  doc/05-Template padrão da Aplicação.md
  doc/img/logoFilaFacil.png
  doc/img/paletadecores.png
Labels: documentation

#63 feat: Padronização página de pedidos
  src/README.md
  src/assets/css/pedidosstyle.css
  src/assets/img/pedidos/logoFilaFacil.png
  src/assets/js/Pedidos.js
  src/assets/js/pedidos.js
  src/pages/Pedidos.html
  src/pages/pedidos.html
Labels: enhancement

#66 doc: Programação de funcionalidades
  doc/06-Programação de Funcionalidades.md
  doc/img/funcionalidades-avaliacao.png
  doc/img/funcionalidades-cadastro.png
  doc/img/funcionalidades-cardapio.png
  doc/img/funcionalidades-compra.png
  doc/img/funcionalidades-filtro.png
  doc/img/funcionalidades-index.png
  doc/img/funcionalidades-login.png
  doc/img/funcionalidades-restaurantes.png
  doc/img/funcionalidades-status.png
  src/README.md
  src/assets/css/login.css
  src/assets/js/login.js
  src/pages/login.html
Labels: documentation

#68 feat: Renderização da página de cardápio via JSON
  src/README.md
  src/assets/img/cardapio/agua.jpg
  src/assets/img/cardapio/brownie-sorvete.jpg
  src/assets/img/cardapio/caipirinha.jpg
  src/assets/img/cardapio/cerveja.jpg
  src/assets/img/cardapio/cha.jpg
  src/assets/img/cardapio/chicken.jpg
  src/assets/img/cardapio/costela.jpg
  src/assets/img/cardapio/duplobacon.jpg
  src/assets/img/cardapio/egg.jpg
  src/assets/img/cardapio/milkshake.jpg
  src/assets/img/cardapio/quatroqueijos.jpg
  src/assets/img/cardapio/refrigerante.jpg
  src/assets/img/cardapio/salada.jpg
  src/assets/img/cardapio/salmao.jpg
  src/assets/js/cardapioCarouselScript.js
  src/assets/js/renderCategoriesCardapioUtils.js
  src/assets/js/renderPratosCardapioUtils.js
  src/assets/js/restauranteJson.js
  src/pages/cardapio.html
Labels: enhancement

#82 feat: Página de perfil
  README.md
  src/README.md
  src/assets/css/perfilStyle.css
  src/assets/js/cadastro.js
  src/assets/js/perfilScript.js
  src/pages/perfil.html
Labels: documentation, enhancement

#80 feat: Adicionado botão de pesquisa funcional na página de cardápio
  src/README.md
  src/assets/css/cardapioStyle.css
  src/assets/js/cardapioCarouselScript.js
  src/assets/js/renderCategoriesCardapioUtils.js
  src/assets/js/renderPratosCardapioUtils.js
  src/pages/cardapio.html
Labels: enhancement

#83 feat: Verificação de contas inexistentes e alteração no redirecionamento ao logar
  src/README.md
  src/assets/js/login.js
Labels: enhancement

#87 fix: Consertar responsividade da pagina de perfil
  src/README.md
  src/assets/css/perfilStyle.css
  src/assets/js/perfilScript.js
Labels: bug
